<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520068248"><DocLocation><![CDATA[C:\frame wrok\TestCases\AddToCompareList]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AddToCompareList]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Java, Silverlight, WinForms.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:15]]></Time>
<TimeTick>1676285835</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[comparelist]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:15]]></Time>
<TimeTick>1676285835</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:15]]></Time>
<TimeTick>1676285835</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:23]]></Time>
<TimeTick>1676285843</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:23]]></Time>
<TimeTick>1676285843</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="User" icon="7" nRep="19" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman2@Rahman.com"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="User" icon="7" nRep="26" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="User" icon="7" nRep="30" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="32" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="User" icon="7" nRep="33" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:24]]></Time>
<TimeTick>1676285844</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Search field Exist]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="User" icon="7" nRep="40" status="Passed" >
<Disp><![CDATA[Search field Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="42" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["computer"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Search ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" >
<Disp><![CDATA[[ Search ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Search Button Exist]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="User" icon="7" nRep="49" status="Passed" >
<Disp><![CDATA[Search Button Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Search ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["[ Search ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Search ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="51" status="Passed" >
<Disp><![CDATA[[ Search ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="55" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA['[ Search ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:27]]></Time>
<TimeTick>1676285847</TimeTick>
<NodeArgs eType="User" icon="7" nRep="56" status="Passed" >
<Disp><![CDATA['[ Search ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ Build your own computer ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:29]]></Time>
<TimeTick>1676285849</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" >
<Disp><![CDATA[[ Build your own computer ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Build your own computer Link is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:29]]></Time>
<TimeTick>1676285849</TimeTick>
<NodeArgs eType="User" icon="7" nRep="59" status="Passed" >
<Disp><![CDATA[Build your own computer Link is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Build your own computer ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:29]]></Time>
<TimeTick>1676285849</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" >
<Disp><![CDATA[[ Build your own computer ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA['[ Build your own computer ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:29]]></Time>
<TimeTick>1676285849</TimeTick>
<NodeArgs eType="User" icon="7" nRep="63" status="Passed" >
<Disp><![CDATA['[ Build your own computer ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Build your own computer  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="65" >
<Disp><![CDATA[[ Build your own computer  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Build your own computer title is present]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<NodeArgs eType="User" icon="7" nRep="66" status="Passed" >
<Disp><![CDATA[Build your own computer title is present]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Build your own computer  ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["[ Build your own computer  ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Build your own computer  ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="68" status="Passed" >
<Disp><![CDATA[[ Build your own computer  ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Add to compare list ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" >
<Disp><![CDATA[[ Add to compare list ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Add to compare list button is present]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<NodeArgs eType="User" icon="7" nRep="73" status="Passed" >
<Disp><![CDATA[Add to compare list button is present]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Add to compare list ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["[ Add to compare list ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:32]]></Time>
<TimeTick>1676285852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Add to compare list ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="75" status="Passed" >
<Disp><![CDATA[[ Add to compare list ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Add to compare list ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:33]]></Time>
<TimeTick>1676285853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="79" >
<Disp><![CDATA[[ Add to compare list ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA['[ Add to compare list ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:33]]></Time>
<TimeTick>1676285853</TimeTick>
<NodeArgs eType="User" icon="7" nRep="80" status="Passed" >
<Disp><![CDATA['[ Add to compare list ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Build your own computer ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="82" >
<Disp><![CDATA[[ Build your own computer ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Product is available in current the page]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<NodeArgs eType="User" icon="7" nRep="83" status="Passed" >
<Disp><![CDATA[Product is available in current the page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Build your own computer ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Link]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["[ Build your own computer ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="86" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Build your own computer ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="85" status="Passed" >
<Disp><![CDATA[[ Build your own computer ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Failed while adding to compare List]]></Obj>
<Details ><![CDATA[FAILED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<NodeArgs eType="User" icon="7" nRep="88" status="Passed" >
<Disp><![CDATA[Failed while adding to compare List]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["shoe"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="91" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="94" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA['[ Search ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:34]]></Time>
<TimeTick>1676285854</TimeTick>
<NodeArgs eType="User" icon="7" nRep="95" status="Passed" >
<Disp><![CDATA['[ Search ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Women's Running Shoe ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:36]]></Time>
<TimeTick>1676285856</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="98" >
<Disp><![CDATA[[ Women's Running Shoe ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA['[ Women's Running Shoe ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:36]]></Time>
<TimeTick>1676285856</TimeTick>
<NodeArgs eType="User" icon="7" nRep="99" status="Passed" >
<Disp><![CDATA['[ Women's Running Shoe ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Add to compare list ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:39]]></Time>
<TimeTick>1676285859</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="103" >
<Disp><![CDATA[[ Add to compare list ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA['[ Add to compare list ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:39]]></Time>
<TimeTick>1676285859</TimeTick>
<NodeArgs eType="User" icon="7" nRep="104" status="Passed" >
<Disp><![CDATA['[ Add to compare list ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Remove ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:42]]></Time>
<TimeTick>1676285862</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="107" >
<Disp><![CDATA[[ Remove ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[Remove button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:42]]></Time>
<TimeTick>1676285862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="108" status="Passed" >
<Disp><![CDATA[Remove button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Remove ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:42]]></Time>
<TimeTick>1676285862</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA["[ Remove ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:42]]></Time>
<TimeTick>1676285862</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="111" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Remove ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="110" status="Passed" >
<Disp><![CDATA[[ Remove ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Remove ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:42]]></Time>
<TimeTick>1676285862</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="114" >
<Disp><![CDATA[[ Remove ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA['[ Remove ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:42]]></Time>
<TimeTick>1676285862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="115" status="Passed" >
<Disp><![CDATA['[ Remove ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Clear list ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:45]]></Time>
<TimeTick>1676285865</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="117" >
<Disp><![CDATA[[ Clear list ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[Clearlist link is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:45]]></Time>
<TimeTick>1676285865</TimeTick>
<NodeArgs eType="User" icon="7" nRep="118" status="Passed" >
<Disp><![CDATA[Clearlist link is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Clear list ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Link]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:45]]></Time>
<TimeTick>1676285865</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA["[ Clear list ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:45]]></Time>
<TimeTick>1676285865</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="121" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Clear list ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="120" status="Passed" >
<Disp><![CDATA[[ Clear list ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ Clear list ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:45]]></Time>
<TimeTick>1676285865</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="124" >
<Disp><![CDATA[[ Clear list ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj ><![CDATA['[ Clear list ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:45]]></Time>
<TimeTick>1676285865</TimeTick>
<NodeArgs eType="User" icon="7" nRep="125" status="Passed" >
<Disp><![CDATA['[ Clear list ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ You have no items to compare.  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:47]]></Time>
<TimeTick>1676285867</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="127" >
<Disp><![CDATA[[ You have no items to compare.  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj ><![CDATA[Successfully cleard the the compare cart]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:47]]></Time>
<TimeTick>1676285867</TimeTick>
<NodeArgs eType="User" icon="7" nRep="128" status="Passed" >
<Disp><![CDATA[Successfully cleard the the compare cart]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:47]]></Time>
<TimeTick>1676285867</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="131" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:47]]></Time>
<TimeTick>1676285867</TimeTick>
<NodeArgs eType="User" icon="7" nRep="132" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ Demo Web Shop ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:27:49]]></Time>
<TimeTick>1676285869</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="134" >