<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520068248"><DocLocation><![CDATA[C:\frame wrok\TestCases\orangehrm]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[orangehrm]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:25]]></Time>
<TimeTick>1676382685</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:25]]></Time>
<TimeTick>1676382685</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:25]]></Time>
<TimeTick>1676382685</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="login" SourceLine="0" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63eb912fdb757fafe4d79d054bf68aaa6d0a2efad96e"]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:25]]></Time>
<TimeTick>1676382685</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="login" SourceLine="1" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:25]]></Time>
<TimeTick>1676382685</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="login" SourceLine="2" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" Source="login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 19:21:25" eTime="14-02-2023 - 19:21:25" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[search]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:28]]></Time>
<TimeTick>1676382688</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:28]]></Time>
<TimeTick>1676382688</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:28]]></Time>
<TimeTick>1676382688</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="search" SourceLine="0" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:30]]></Time>
<TimeTick>1676382690</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04321"]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:30]]></Time>
<TimeTick>1676382690</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" Source="search" SourceLine="1" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:30]]></Time>
<TimeTick>1676382690</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" Source="search" SourceLine="2" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" Source="search" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="25" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 19:21:25" eTime="14-02-2023 - 19:21:30" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="21" >
<Disp><![CDATA[search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[add]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:30]]></Time>
<TimeTick>1676382690</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:30]]></Time>
<TimeTick>1676382690</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:30]]></Time>
<TimeTick>1676382690</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="42" Source="add" SourceLine="0" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" Source="add" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:31]]></Time>
<TimeTick>1676382691</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["nish"]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:31]]></Time>
<TimeTick>1676382691</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="47" Source="add" SourceLine="1" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[middleName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mary"]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:31]]></Time>
<TimeTick>1676382691</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" Source="add" SourceLine="2" >
<Disp><![CDATA[middleName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["d"]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:31]]></Time>
<TimeTick>1676382691</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" Source="add" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:31]]></Time>
<TimeTick>1676382691</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" Source="add" SourceLine="4" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" Source="add" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:52]]></Time>
<TimeTick>1676382712</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WebElement]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"WebElement"&nbsp;(of&nbsp;class&nbsp;WebElement).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:52]]></Time>
<TimeTick>1676382712</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[WebElement]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebElement<br>Index = 7<br>Html Tag = I<br>_xpath = //DIV[2]/DIV[1]/DIV[2]/DIV[1]/DIV[1]/DIV[2]/I[1]<br>|Visible = -1<br>innertext = <br>Html Id = <br>DHTML Class = oxd-icon bi-caret-up-fill oxd-select-text--arrow<br>acc_name = <br>]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:52]]></Time>
<TimeTick>1676382712</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="96" status="Warning" nType="Description" Source="add" SourceLine="5" >
<Disp><![CDATA[WebElement]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="95" status="Failed" nType="Run Error" Source="add" SourceLine="5" >
<Disp><![CDATA[WebElement]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="94" status="Failed" Source="add" SourceLine="5" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="40" status="Failed" Source="add" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:52]]></Time>
<TimeTick>1676382712</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;WebElement&quot; (of class WebElement).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (6): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM_3&quot;).WebElement(&quot;WebElement&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[14-02-2023 - 19:21:52]]></Time>
<TimeTick>1676382712</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="98" status="Failed" Source="add" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[590240]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14-02-2023 - 19:22:08]]></Time>
<TimeTick>1676382728</TimeTick>
<NodeArgs eType="General" icon="12" nRep="99" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="97" status="Failed" Source="add" SourceLine="5" >
<Disp><![CDATA[OrangeHRM]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[590240]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 19:21:30" eTime="14-02-2023 - 19:22:09" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="37" status="Failed" >
<Disp><![CDATA[add Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[orangehrm Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 19:21:18" eTime="14-02-2023 - 19:22:09" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test orangehrm Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>