<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520068248"><DocLocation><![CDATA[C:\frame wrok\TestCases\Register]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Register]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Java, Silverlight, WinForms.]]></Details>
<Time><![CDATA[13-02-2023 - 16:30:52]]></Time>
<TimeTick>1676286052</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[register]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 16:30:53]]></Time>
<TimeTick>1676286053</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 16:30:53]]></Time>
<TimeTick>1676286053</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Register ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:00]]></Time>
<TimeTick>1676286060</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ Register ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA['[ Register ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:00]]></Time>
<TimeTick>1676286060</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA['[ Register ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ FirstName ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 10000]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:01]]></Time>
<TimeTick>1676286061</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[[ FirstName ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Gender ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["M"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" >
<Disp><![CDATA[[ Gender ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Value - 'M' selected from Drop Down Field - '[ Gender ] radio button group']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Value - 'M' selected from Drop Down Field - '[ Gender ] radio button group']]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ FirstName ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[[ FirstName ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[First name field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="User" icon="7" nRep="26" status="Passed" >
<Disp><![CDATA[First name field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ FirstName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["[ FirstName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ FirstName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="28" status="Passed" >
<Disp><![CDATA[[ FirstName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ FirstName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["[ FirstName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="32" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ FirstName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="31" status="Passed" >
<Disp><![CDATA[[ FirstName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ FirstName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["[ FirstName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ FirstName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="34" status="Passed" >
<Disp><![CDATA[[ FirstName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ FirstName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["[ FirstName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="38" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ FirstName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="37" status="Passed" >
<Disp><![CDATA[[ FirstName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ FirstName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mujibur"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" >
<Disp><![CDATA[[ FirstName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Value - 'Mujibur' entered in Field - '[ FirstName ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="User" icon="7" nRep="42" status="Passed" >
<Disp><![CDATA[Value - 'Mujibur' entered in Field - '[ FirstName ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ LastName ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" >
<Disp><![CDATA[[ LastName ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Last name field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="User" icon="7" nRep="45" status="Passed" >
<Disp><![CDATA[Last name field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ LastName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["[ LastName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ LastName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="47" status="Passed" >
<Disp><![CDATA[[ LastName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ LastName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["[ LastName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="51" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ LastName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="50" status="Passed" >
<Disp><![CDATA[[ LastName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ LastName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["[ LastName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ LastName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="53" status="Passed" >
<Disp><![CDATA[[ LastName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ LastName ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA["[ LastName ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ LastName ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="56" status="Passed" >
<Disp><![CDATA[[ LastName ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ LastName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" >
<Disp><![CDATA[[ LastName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Value - 'Rahman' entered in Field - '[ LastName ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="User" icon="7" nRep="61" status="Passed" >
<Disp><![CDATA[Value - 'Rahman' entered in Field - '[ LastName ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="User" icon="7" nRep="64" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="66" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="69" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:02]]></Time>
<TimeTick>1676286062</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="72" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="76" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="75" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman832@Rahman.com"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Value - 'Rahman832@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="User" icon="7" nRep="80" status="Passed" >
<Disp><![CDATA[Value - 'Rahman832@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="User" icon="7" nRep="83" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="85" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="89" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="88" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="92" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="91" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="95" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="94" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="98" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="User" icon="7" nRep="99" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ ConfirmPassword ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="101" >
<Disp><![CDATA[[ ConfirmPassword ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[Password field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="User" icon="7" nRep="102" status="Passed" >
<Disp><![CDATA[Password field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ ConfirmPassword ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA["[ ConfirmPassword ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="105" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ ConfirmPassword ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="104" status="Passed" >
<Disp><![CDATA[[ ConfirmPassword ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ ConfirmPassword ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA["[ ConfirmPassword ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="108" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ ConfirmPassword ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="107" status="Passed" >
<Disp><![CDATA[[ ConfirmPassword ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ ConfirmPassword ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA["[ ConfirmPassword ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="111" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ ConfirmPassword ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="110" status="Passed" >
<Disp><![CDATA[[ ConfirmPassword ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ ConfirmPassword ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA["[ ConfirmPassword ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="114" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ ConfirmPassword ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="113" status="Passed" >
<Disp><![CDATA[[ ConfirmPassword ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ ConfirmPassword ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:31:03]]></Time>
<TimeTick>1676286063</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA["[ ConfirmPassword ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>