<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520068248"><DocLocation><![CDATA[C:\frame wrok\TestCases\AddToWIshlist]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AddToWIshlist]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Java, Silverlight, WinForms.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:27]]></Time>
<TimeTick>1676285907</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[wishlist]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:28]]></Time>
<TimeTick>1676285908</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:28]]></Time>
<TimeTick>1676285908</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:36]]></Time>
<TimeTick>1676285916</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:36]]></Time>
<TimeTick>1676285916</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="User" icon="7" nRep="19" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman2@Rahman.com"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="User" icon="7" nRep="26" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="User" icon="7" nRep="30" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="32" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="User" icon="7" nRep="33" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:37]]></Time>
<TimeTick>1676285917</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Search field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="User" icon="7" nRep="40" status="Passed" >
<Disp><![CDATA[Search field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="42" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="45" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="49" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="48" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="51" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["belt"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Value - 'belt' entered in Field - '[ q ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="User" icon="7" nRep="56" status="Passed" >
<Disp><![CDATA[Value - 'belt' entered in Field - '[ q ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Search ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" >
<Disp><![CDATA[[ Search ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[Search button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="User" icon="7" nRep="59" status="Passed" >
<Disp><![CDATA[Search button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="62" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA['[ Search ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="User" icon="7" nRep="63" status="Passed" >
<Disp><![CDATA['[ Search ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Search item not avaiable]]></Obj>
<Details ><![CDATA[FAILED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:41]]></Time>
<TimeTick>1676285921</TimeTick>
<NodeArgs eType="User" icon="7" nRep="64" status="Passed" >
<Disp><![CDATA[Search item not avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Tricentis Demo Web Shop ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:44]]></Time>
<TimeTick>1676285924</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" >
<Disp><![CDATA[[ Tricentis Demo Web Shop ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:45]]></Time>
<TimeTick>1676285925</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Search field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:45]]></Time>
<TimeTick>1676285925</TimeTick>
<NodeArgs eType="User" icon="7" nRep="70" status="Passed" >
<Disp><![CDATA[Search field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="72" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="76" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="75" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="78" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="81" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Used Phone"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Value - 'Used Phone' entered in Field - '[ q ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="User" icon="7" nRep="86" status="Passed" >
<Disp><![CDATA[Value - 'Used Phone' entered in Field - '[ q ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Search ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="88" >
<Disp><![CDATA[[ Search ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Search button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="User" icon="7" nRep="89" status="Passed" >
<Disp><![CDATA[Search button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="92" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA['[ Search ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:46]]></Time>
<TimeTick>1676285926</TimeTick>
<NodeArgs eType="User" icon="7" nRep="93" status="Passed" >
<Disp><![CDATA['[ Search ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Used phone ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:49]]></Time>
<TimeTick>1676285929</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="96" >
<Disp><![CDATA[[ Used phone ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA['[ Used phone ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:28:49]]></Time>
<TimeTick>1676285929</TimeTick>
<NodeArgs eType="User" icon="7" nRep="97" status="Passed" >
<Disp><![CDATA['[ Used phone ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:12]]></Time>
<TimeTick>1676285952</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="218" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Wishlist button is not available is not available]]></Obj>
<Details ><![CDATA[FAILED]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:12]]></Time>
<TimeTick>1676285952</TimeTick>
<NodeArgs eType="User" icon="7" nRep="219" status="Failed" >
<Disp><![CDATA[Wishlist button is not available is not available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ bar-notification ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:15]]></Time>
<TimeTick>1676285955</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="221" >
<Disp><![CDATA[[ bar-notification ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[WHISHLIST ADDED ]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:15]]></Time>
<TimeTick>1676285955</TimeTick>
<NodeArgs eType="User" icon="7" nRep="222" status="Passed" >
<Disp><![CDATA[WHISHLIST ADDED ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ Wishlist ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:15]]></Time>
<TimeTick>1676285955</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="225" >
<Disp><![CDATA[[ Wishlist ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Link ].GetROProperty "innerhtml"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:39]]></Time>
<TimeTick>1676285979</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="267" status="Warning" >
<Disp><![CDATA[[ Link ].GetROProperty "innerhtml"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:39]]></Time>
<TimeTick>1676285979</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>xpath = //TD/A[normalize-space()='Used phone']<br>Mercury Class = Link<br>]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:39]]></Time>
<TimeTick>1676285979</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="269" status="Warning" nType="Description" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="268" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;[ Link ]&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\frame wrok\Resources\AppSpecificFL\AppSpecFL.qfl<BR/>Line (631): &quot;    y=Browser(&quot;name:=Demo Web Shop. Wishlist.*&quot;).Page(&quot;title:=Demo Web Shop. Wishlist.*&quot;).Link(&quot;xpath:=//TD/A[normalize-space()='Used phone']&quot;).GetROProperty(&quot;innerhtml&quot;)&quot;.]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:39]]></Time>
<TimeTick>1676285979</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="270" status="Failed" Source="C:\frame wrok\Resources\AppSpecificFL\AppSpecFL.qfl" SourceLine="630" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[1183596]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[13-02-2023 - 16:29:44]]></Time>
<TimeTick>1676285984</TimeTick>
<NodeArgs eType="General" icon="13" nRep="271" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-02-2023 - 16:28:27" eTime="13-02-2023 - 16:29:44" passed="27" failed="3" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[wishlist Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[AddToWIshlist Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-02-2023 - 16:28:26" eTime="13-02-2023 - 16:29:44" passed="27" failed="3" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test AddToWIshlist Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>