<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520068248"><DocLocation><![CDATA[C:\frame wrok\TestCases\asian_paint]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[asian_paint]]></DName>
<Res><![CDATA[Res13]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Trusted Wall Painting,]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:13]]></Time>
<TimeTick>1676441173</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Trusted Wall Painting,]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:13]]></Time>
<TimeTick>1676441173</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:13]]></Time>
<TimeTick>1676441173</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Action1" SourceLine="5" >
<Disp><![CDATA[WebElement.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[MOBILE_NUMBER.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6384608096"]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:13]]></Time>
<TimeTick>1676441173</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="6" >
<Disp><![CDATA[MOBILE_NUMBER.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA["SUBMIT"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (7 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=submit<br>role=<br>name=SUBMIT<br>micclass=WebButton<br>html tag=BUTTON<br>acc_name=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (48 objects found)&nbsp;</FONT></u><br>
micclass=WebButton<br>html tag=BUTTON<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=SUBMIT<SPAN class=passed> (Used</SPAN>, 7 matches)</SPAN><br>type=submit<SPAN class=passed> (Used</SPAN>, 7 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 5 matches)</SPAN><br>value=SUBMIT<SPAN class=passed> (Used</SPAN>, 5 matches)</SPAN><br>class=ctaText modal__variant-login--submit<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:13]]></Time>
<TimeTick>1676441173</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Action1" SourceLine="7" >
<Disp><![CDATA["SUBMIT"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SUBMIT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:13]]></Time>
<TimeTick>1676441173</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="20" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SUBMIT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[LOGIN_OTP.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["49828"]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="Action1" SourceLine="8" >
<Disp><![CDATA[LOGIN_OTP.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[SUBMIT_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="Action1" SourceLine="9" >
<Disp><![CDATA[SUBMIT_2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Trusted Wall Painting,]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Trusted Wall Painting,]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 11:36:13" eTime="15-02-2023 - 11:36:14" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[select]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Trusted Wall Painting,]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Trusted Wall Painting,]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Furniture design ideas.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="33" Source="select" SourceLine="0" >
<Disp><![CDATA[Furniture design ideas.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Furniture design ideas.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="36" Source="select" SourceLine="1" >
<Disp><![CDATA[Furniture design ideas.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Furniture design ideas.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="39" Source="select" SourceLine="2" >
<Disp><![CDATA[Furniture design ideas.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Furniture design ideas.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:14]]></Time>
<TimeTick>1676441174</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="42" Source="select" SourceLine="3" >
<Disp><![CDATA[Furniture design ideas.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[BOOK AN APPOINTMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:15]]></Time>
<TimeTick>1676441175</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="45" Source="select" SourceLine="4" >
<Disp><![CDATA[BOOK AN APPOINTMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="select" SourceLine="0" >
<Disp><![CDATA[Trusted Wall Painting,]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Interior Design: House]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:42]]></Time>
<TimeTick>1676441202</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[bhs-spaces-we-transform-bedroo.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:42]]></Time>
<TimeTick>1676441202</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="49" Source="select" SourceLine="5" >
<Disp><![CDATA[bhs-spaces-we-transform-bedroo.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[bhs-spaces-we-transform-bedroo.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:42]]></Time>
<TimeTick>1676441202</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="52" Source="select" SourceLine="6" >
<Disp><![CDATA[bhs-spaces-we-transform-bedroo.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[EXPLORE NOW.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:42]]></Time>
<TimeTick>1676441202</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="55" Source="select" SourceLine="7" >
<Disp><![CDATA[EXPLORE NOW.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" Source="select" SourceLine="5" >
<Disp><![CDATA[Interior Design: House]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Bedroom Design: Bedroom]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:47]]></Time>
<TimeTick>1676441207</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Minimalist Bedroom Design.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:47]]></Time>
<TimeTick>1676441207</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="59" Source="select" SourceLine="8" >
<Disp><![CDATA[Minimalist Bedroom Design.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Minimalist Bedroom Design.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 11:36:47]]></Time>
<TimeTick>1676441207</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="62" Source="select" SourceLine="9" >
<Disp><![CDATA[Minimalist Bedroom Design.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[".localities-container{color:#f"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[15-02-2023 - 11:37:09]]></Time>
<TimeTick>1676441229</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="93" status="Warning" Source="select" SourceLine="10" >
<Disp><![CDATA[".localities-container{color:#f"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[".localities-container{color:#f"- Smart Identification]]></Obj>